
symbols = {
  "Air Liquide": "AI.PA",
  "Airbus SE": "AIR.PA",
  "Alstom": "ALO.PA",
  "ArcelorMittal": "MT.AS",
  "AXA": "CS.PA",
  "BNP Paribas": "BNP.PA",
  "Bouygues": "EN.PA",
  "Capgemini": "CAP.PA",
  "Carrefour": "CA.PA",
  "Crédit Agricole": "ACA.PA",
  "Danone": "BN.PA",
  "Dassault Systèmes": "DSY.PA",
  "Edenred": "EDEN.PA",
  "Engie": "ENGI.PA",
  "EssilorLuxottica": "EL.PA",
  "Eurofins Scientific": "ERF.PA",
  "Hermès International": "RMS.PA",
  "Kering": "KER.PA",
  "L'Oréal": "OR.PA",
  "Legrand": "LR.PA",
  "LVMH": "MC.PA",
  "Michelin": "ML.PA",
  "Orange": "ORA.PA",
  "Pernod-Ricard": "RI.PA",
  "Publicis Groupe": "PUB.PA",
  "Renault": "RNO.PA",
  "Safran": "SAF.PA",
  "Saint-Gobain": "SGO.PA",
  "Sanofi": "SAN.PA",
  "Schneider Electric": "SU.PA",
  "Société Générale": "GLE.PA",
  "Stellantis NV": "STLA.PA",
  "STMicroelectronics": "STM.PA",
  "Teleperformance": "TEP.PA",
  "Thales": "HO.PA",
  "TotalEnergies SE": "TTE.PA",
  "Unibail Rodamco Westfield": "URW.AS",
  "Veolia Environnement": "VIE.PA",
  "Vinci": "DG.PA",
  "Vivendi": "VIV.PA"
}
